# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: chmod 744 install_docker-way.sh ; ./install_docker-way.sh
workflows:
  limited_building:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 16 * * *"
          filters:
            branches:
              only:
                - master
