# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: chmod 744 DockerHub_Update.sh ; ./DockerHub_Update.sh
workflows:
  version: 2
  limited_building:
    triggers:
      - schedule:
          cron: "0 18 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
#      - hold:
#          type: approval    
      - build:
#          requires:
#            - hold
